### PR TITLE
removed hotspot prediction files

### PR DESCRIPTION
**Pull request by jradrion**
- removing exploratory/experimental code for hotspot prediction

### CODE REVIEW

**Comment by andrewkern** [comment]
taking this all out @jradrion?

**Comment by jradrion** [comment]
Was just about to ask you what you thought about it? I was just trying to avoid further confusion. I'm fine with leaving it in too.

**Comment by andrewkern** [comment]
Okay here's an idea-- what if you push those scripts/functions to a different, "experimental" branch?

**Comment by jradrion** [comment]
Works for me. I'm going to have to put this on pause right now but I'll get it done today.

**Comment by jradrion** [comment]
OK, going to merge/close this PR and push the affected files to a new branch named `experimental_hotspots`.

**Pull request merged**
